language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_script:
 - wget https://scrutinizer-ci.com/ocular.phar

script:
 - phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
 - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
